### ISSUE TITLE
Implement command to provide horoscope 

### ISSUE THREAD

**Issue by nuclearcat** [dcryys/Themis#4]
As one of participants requested, it will be cool if bot provide horoscope.

**Comment by dcryys** [comment]
Hello! How exactly do you want the command to work? Send me some details, please.

**Comment by nuclearcat** [comment]
I would like to get the horoscope for my sign of zodiac for next week and perhaps it may include some funny instructions.
So command might be /horoscope <zodiacsign>, like
```
/horoscope Leo
```
